import Head from 'next/head'
import Image from 'next/image'
// import Header from '../components/Header'
import styles from '../styles/Home.module.css'

const mobileMenuToggle = (event) =>
{
  event.target.classList.toggle('active')
  document.querySelector('#app').classList.toggle('mobile_menu_on')
}

const handlePopupToggle = () => {
  document.querySelector('#app').classList.toggle('faq_popup_on')
}

export default function Home() {
  return (
    <div id={"app"}>
      <Head>
        <title>Lunar Assistant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className="logo">
            <img src="/images/logo.png" />
            <h1>
                <span>LUNAR</span>
                <span><span className="yellow_border_bottom">A</span>SSISTANT</span>
            </h1>
        </div>

        <div id="hamburger_wrapper">
            <button onClick={mobileMenuToggle}></button>
            <div className="meat">
                <div className="meat_last"></div>
            </div>
        </div>

        <nav id="main_navigation">
            <a href="#">BUY</a>
            <a href="#">EARN</a>
            <a href="https://guide.lunarassistant.com/">DOCS</a>
            <a href="#" className="dashboard">DASHBOARD</a>

            <div className="social_bar">
                <a href="https://discord.gg/eMNdhXqKjk">
                    <img src="/svgs/discord.svg" />
                </a>
                <a href="https://twitter.com/GraviDAO_">
                    <img src="/svgs/twitter.svg" />
                </a>
                <a href="https://github.com/GraviDAO">
                    <img src="/svgs/github.svg" />
                </a>
            </div>
        </nav>
    </header>

      <main className={styles.main}>
        <h2>Enable your Discord&nbsp;DAO</h2>
          <ul>
              <li>Verifiable ownership</li>
              <li>Dynamic role distribution</li>
              <li>Token-weighted polling</li>
          </ul>
          <a className="button" href="https://discord.com/api/oauth2/authorize?client_id=893178480303407135&permissions=268435456&scope=applications.commands%20bot">Add to server</a>
      </main>

      <footer className={styles.footer}>
        <button className="button" id="popup_button" onClick={handlePopupToggle}>?</button>
        <Image src="/images/hand_orb.png" className="hand_orb" alt="hand holding orb" layout="fill" />
        <div className="social_bar">
          <a href="https://discord.gg/eMNdhXqKjk">
              <Image src="/svgs/discord.svg" alt="Discord logo" width={30} height={30} />
          </a>
          <a href="https://twitter.com/GraviDAO_">
              <Image src="/svgs/twitter.svg" alt="Twitter logo" width={30} height={30} />
          </a>
          <a href="https://github.com/GraviDAO">
              <Image src="/svgs/github.svg" alt="Github logo" width={30} height={30} />
          </a>
        </div>
      </footer>

      <div className="blur_overlay" onClick={handlePopupToggle}></div>

      <div className="faq_popup">
          <p>Lunar Assistant is a Discord bot developed for the Terra Ecosystem community.</p>
          <p>Most of our features are free of charge.If you wish to use the dashboard to managecomplex role distributions and organize polls,please buy a Lunar Assistant NFT and stakeit on our WebApp.</p>
          <p>For more information, visit our docs.</p>
      </div>
    </div>
  )
}
